#https://david.dev/how-to-install-mariadb-phpmyadmin-with-docker-compose
version: '3'

volumes:
  mariadb:
    driver: local

networks:
    db:
        driver: bridge

services:
  node:
    build:
     context: .
    ports:
      - 5000:8080
    environment:
      - SERVER_PORT=8080
      - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017/notes
    volumes:
      - .:/code
    depends_on:
      - mariadb
    networks:
      db:
    
  mariadb:
    container_name: db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_USER:  formation
      MYSQL_PASSWORD: formation49+
    expose:
        - "5001"
    ports:
        - "5001:3306"
    volumes:
     - mariadb:/var/lib/mysql
    networks:
      db:
              
  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "5002"
    ports:
      - "5002:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306 
    networks:
      db:

# docker compose -f docker-compose.yml  --project-name api-liveaddict up -d --remove-orphans --force-recreate
#to run : docker-compose --project-name liveaddict_bdd up -d --remove-orphans
#to run : docker-compose start/stop 
# redémarrage du service : Net stop com.docker.service / Net start com.docker.service
#& 'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchDaemon 

# git clone https://clemFormation@github.com/clemFormation/api-liveaddict.git
# docker compose down